#!/bin/bash

# Interface for the MAVlink messaging experiment

##### Constants
DB_FILE="database.db"
TEMP_FILE="/tmp/sqltemp"
# SQL QUERIES
DB_SESSION_TABLE="CREATE TABLE IF NOT EXISTS session (\
	id INTEGER NOT NULL, \
	date_time TEXT NOT NULL, \
	description TEXT NOT NULL, \
	PRIMARY KEY (id));"
DB_RECORDS_TABLE="CREATE TABLE IF NOT EXISTS records (\
	session_id INTEGER NOT NULL, \
	frame_seq INTEGER NOT NULL, \
	frame_contents BLOB NOT NULL, \
	time_sent TEXT NOT NULL, \
	msg_size INTEGER NOT NULL, \
	rtt REAL NOT NULL, \
	uplink_time REAL NOT NULL, \
	downlink_time REAL NOT NULL, \
	PRIMARY KEY (session_id, frame_seq), \
	FOREIGN KEY (session_id) REFERENCES session(id));"

##### Functions

function usage {
	echo "usage.."
	echo "./start [-c | -s] [-m communication type]"
	echo "	-c or -s: client-side or server-side, only one option may be used"
	echo "	-m: communication type(type in 433, 915, blue or bluetooth)"
}

function start_915 {
	return
}

function start_433 {
	return
}

function start_wifi {
	return
}

function start_bluetooth {
	return
}

function init_db {
	if [ ! -f $DB_FILE ]; then
		echo "database.db not found!"
		echo "Creating new database file with predefined schema.."
		echo $DB_SESSION_TABLE > $TEMP_FILE
		echo $DB_RECORDS_TABLE >> $TEMP_FILE
		cat $TEMP_FILE
		sqlite3 $DB_FILE < $TEMP_FILE
		rm -f $TEMP_FILE
	else
		echo "Initialising DB.."
		echo $DB_SESSION_TABLE > $TEMP_FILE
		echo $DB_RECORDS_TABLE >> $TEMP_FILE
		cat $TEMP_FILE
		sqlite3 $DB_FILE < $TEMP_FILE
		rm -f $TEMP_FILE
	fi
}

##### Main

if [ $# -ne 3 ]; then
	usage
	exit 1
fi

if [ $2 != "-m" ]; then
	usage
	exit 1
fi

case $1 in
	"-c" )
		echo "Client-side testing.."
		case $3 in
			"433" )
				echo "433MHz sik radio selected!"
				start_433
				;;
			"915" )
				echo "915MHz sik radio selected!"
				;;
			"wifi" )
				echo "wifi selected!"
				;;
			"bluetooth" )
				echo "bluetooth selected!"
				;;
			* )
				usage
				exit 1
				;;
		esac
		;;
	"-s" )
		echo "Server-side testing.."
		case $3 in
			"433" )
				echo "433MHz sik radio selected!"
				;;
			"915" )
				echo "915MHz sik radio selected!"
				;;
			"wifi" )
				echo "wifi selected!"
				;;
			"bluetooth" )
				echo "bluetooth selected!"
				;;
			* )
				usage
				exit 1
				;;
		esac
		;;
	* )
		usage
		exit 1
		;;
esac

