#!/bin/bash

##### Constants
CONFIG_SH="config.sh"

##### Functions

function usage {
	echo "usage.."
	echo "./start [-c | -s] [-m communication type]"
	echo "	-c or -s: client-side or server-side, only one option may be used"
	echo "	-m: communication type(type in 433, 915, blue or bluetooth)"
}

function start_915 {
	return
}

function start_433 {
	return
}

function start_wifi {
	return
}

function start_bluetooth {
	return
}

function init_db {
	if [ ! -f $DB_FILE ]; then
		echo "database.db not found!"
		echo "Creating new database file with predefined schema.."
		echo $DB_SESSION_TABLE > $TEMP_FILE
		echo $DB_RECORDS_TABLE >> $TEMP_FILE
		cat $TEMP_FILE
		sqlite3 $DB_FILE < $TEMP_FILE
		rm -f $TEMP_FILE
	else
		echo "Initialising DB.."
		echo $DB_SESSION_TABLE > $TEMP_FILE
		echo $DB_RECORDS_TABLE >> $TEMP_FILE
		cat $TEMP_FILE
		sqlite3 $DB_FILE < $TEMP_FILE
		rm -f $TEMP_FILE
	fi
}

##### Main

# Argument check
if [ $# -ne 3 ]; then
	usage
	exit 1
fi
if [ $2 != "-m" ]; then
	usage
	exit 1
fi

# Source config script
. $CONFIG_SH

# Initialise database file
init_db

# Actual procedure
case $1 in
	"-c" )
		echo "Client-side testing.."
		case $3 in
			"433" )
				echo "433MHz sik radio selected!"
				start_433
				;;
			"915" )
				echo "915MHz sik radio selected!"
				;;
			"wifi" )
				echo "wifi selected!"
				;;
			"bluetooth" )
				echo "bluetooth selected!"
				;;
			* )
				usage
				exit 1
				;;
		esac
		;;
	"-s" )
		echo "Server-side testing.."
		case $3 in
			"433" )
				echo "433MHz sik radio selected!"
				;;
			"915" )
				echo "915MHz sik radio selected!"
				;;
			"wifi" )
				echo "wifi selected!"
				;;
			"bluetooth" )
				echo "bluetooth selected!"
				;;
			* )
				usage
				exit 1
				;;
		esac
		;;
	* )
		usage
		exit 1
		;;
esac

